import type { ClassDefinition } from '../types/class'

export const CLASSES: ClassDefinition[] = [
  {
    name: 'Dreadnought',
    description: 'An unstoppable fighter that thrives in the heat of battle.',
    mainAttribute: 'might',
    hpBase: 14,
    recuperationDie: 'd10',
    primaryResourceName: 'Fury',
    primaryResourceMax: 6,
    primaryResourceRechargeDie: '1d4',
    secondaryResourceName: null,
    secondaryResourceMax: null,
    weaponCompetencies: ['Medium Melee', 'Heavy Melee'],
    armorCompetencies: ['Light', 'Heavy'],
    classPerks: [
      {
        id: 'dreadnought-perk-1',
        name: 'Shieldbreaker',
        description:
          'Melee attacks gain +1 Armor Penetration (ignore 1 AV); +2 at Level 5, +3 at Level 9.',
      },
      {
        id: 'dreadnought-perk-2',
        name: 'Unyielding',
        description: 'When reduced below half HP, gain +1 to all attack rolls until end of combat.',
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Driftwalker',
    description: 'An occult caster specializing in blood magicks and dark bargains.',
    mainAttribute: 'mind',
    hpBase: 10,
    recuperationDie: 'd6',
    primaryResourceName: 'Bile',
    primaryResourceMax: 6,
    primaryResourceRechargeDie: '1d4',
    secondaryResourceName: 'Blood (HP)',
    secondaryResourceMax: null,
    weaponCompetencies: ['Light Melee'],
    armorCompetencies: ['Light'],
    classPerks: [
      {
        id: 'driftwalker-perk-1',
        name: 'Dark Bargain',
        description: 'Once per Full Rest, spend HP instead of Bile for a power at a 2:1 ratio.',
      },
      {
        id: 'driftwalker-perk-2',
        name: 'Occult Resilience',
        description: 'Gain +1 MR permanently.',
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Fell Hunter',
    description: 'A deadly marksman with heightened senses and an axe to grind with the demonic.',
    mainAttribute: 'agility',
    hpBase: 10,
    recuperationDie: 'd8',
    primaryResourceName: 'Focus',
    primaryResourceMax: 6,
    primaryResourceRechargeDie: '1d4',
    secondaryResourceName: null,
    secondaryResourceMax: null,
    weaponCompetencies: ['Light Melee', 'Ranged Light', 'Ranged Heavy', 'Thrown Light'],
    armorCompetencies: ['Light'],
    classPerks: [
      {
        id: 'fell-hunter-perk-1',
        name: 'Demon Slayer',
        description: 'Deal +HL bonus damage against Fell (demonic) enemies.',
      },
      {
        id: 'fell-hunter-perk-2',
        name: 'Tracker',
        description: 'Gain Benefit on all checks to track, hunt, or survive in the wilderness.',
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Judge',
    description: 'A righteous warrior powered by the Divine and fighting for justice.',
    mainAttribute: 'might',
    hpBase: 12,
    recuperationDie: 'd8',
    primaryResourceName: 'Fervor',
    primaryResourceMax: 6,
    primaryResourceRechargeDie: '1d4',
    secondaryResourceName: null,
    secondaryResourceMax: null,
    weaponCompetencies: ['Light Melee', 'Medium Melee'],
    armorCompetencies: ['Light', 'Heavy'],
    classPerks: [
      {
        id: 'judge-perk-1',
        name: 'Divine Authority',
        description: 'Gain Benefit on social checks when invoking justice or the law.',
      },
      {
        id: 'judge-perk-2',
        name: 'Holy Warrior',
        description: 'Once per Full Rest, deal +2d6 Divine damage on one successful attack.',
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Mystic',
    description: 'A student of the magickal arts that manipulates and bends reality to her will.',
    mainAttribute: 'mind',
    hpBase: 8,
    recuperationDie: 'd6',
    primaryResourceName: 'Mana',
    primaryResourceMax: 8,
    primaryResourceRechargeDie: '1d6',
    secondaryResourceName: null,
    secondaryResourceMax: null,
    weaponCompetencies: ['Light Melee', 'Ranged Light'],
    armorCompetencies: ['Light'],
    classPerks: [
      {
        id: 'mystic-perk-1',
        name: 'Arcane Focus',
        description: 'Once per Full Rest, cast a power without spending Mana.',
      },
      {
        id: 'mystic-perk-2',
        name: 'Elemental Affinity',
        description: 'Choose one element; powers of that type deal +HL bonus damage.',
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Phantom',
    description: 'An agile fighter utilizing shadow and guile to strike with lethal impact.',
    mainAttribute: 'agility',
    hpBase: 10,
    recuperationDie: 'd8',
    primaryResourceName: 'Guile',
    primaryResourceMax: 6,
    primaryResourceRechargeDie: '1d4',
    secondaryResourceName: null,
    secondaryResourceMax: null,
    weaponCompetencies: ['Light Melee', 'Medium Melee'],
    armorCompetencies: ['Light'],
    classPerks: [
      {
        id: 'phantom-perk-1',
        name: 'Shadow Step',
        description: 'Once per round, move up to Nearby range without provoking Provoked Attacks.',
      },
      {
        id: 'phantom-perk-2',
        name: 'Backstab',
        description: 'Deal +HL damage when attacking a target that is flanked or unaware.',
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Priest',
    description:
      'A pious caster that wields her faith as a weapon while bolstering and healing allies.',
    mainAttribute: 'mind',
    hpBase: 10,
    recuperationDie: 'd6',
    primaryResourceName: 'Faith',
    primaryResourceMax: 8,
    primaryResourceRechargeDie: '1d6',
    secondaryResourceName: 'Healing Charges',
    secondaryResourceMax: 3,
    weaponCompetencies: ['Light Melee', 'Medium Melee'],
    armorCompetencies: ['Light'],
    classPerks: [
      {
        id: 'priest-perk-1',
        name: 'Divine Healer',
        description: 'Healing powers restore +HL additional HP.',
      },
      {
        id: 'priest-perk-2',
        name: 'Purifying Light',
        description: 'Once per Full Rest, cure all Diseases and Status Effects from one ally.',
      },
    ],
    classPaths: [
      {
        id: 'chaplain',
        name: 'Chaplain',
        description:
          "You are focused on the strict study of holy texts and understanding the divine song that flows from your god to you. The healing arts and accepting your god's grace come easily to you.",
        primaryResourceMax: 10,
        primaryResourceRechargeDie: '1d6',
        secondaryResourceMax: 4,
      },
      {
        id: 'warpriest',
        name: 'War Priest',
        description:
          'You are the physical embodiment of the fury of your god. You understand that in order to make your gospel heard by the heretic, you must get up close and personal. Your will is iron and your body is steel.',
        primaryResourceMax: 6,
        primaryResourceRechargeDie: '1d4',
        secondaryResourceMax: 3,
        additionalArmorCompetencies: ['Heavy', 'Shield'],
        additionalWeaponCompetencies: ['Heavy Melee'],
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Primalist',
    description:
      'A hybrid warrior harnessing the power of nature to call down the elements and augment his body.',
    mainAttribute: 'might',
    hpBase: 11,
    recuperationDie: 'd8',
    primaryResourceName: 'Spirit',
    primaryResourceMax: 6,
    primaryResourceRechargeDie: '1d4',
    secondaryResourceName: 'Ferocity',
    secondaryResourceMax: 6,
    weaponCompetencies: ['Light Melee', 'Medium Melee', 'Ranged Light'],
    armorCompetencies: ['Light'],
    classPerks: [
      {
        id: 'primalist-perk-1',
        name: "Nature's Wrath",
        description: 'Elemental powers deal +1 damage per Spirit spent above the base cost.',
      },
      {
        id: 'primalist-perk-2',
        name: 'Beast Form',
        description: 'Once per Full Rest, gain +2 MIGHT and +2 Speed for 3 rounds.',
      },
    ],
    startingArtifactCapacity: 1,
  },
  {
    name: 'Sentinel',
    description: 'The perfect soldier that was designed to protect and defend.',
    mainAttribute: 'might',
    hpBase: 12,
    recuperationDie: 'd10',
    primaryResourceName: 'Discipline',
    primaryResourceMax: 8,
    primaryResourceRechargeDie: '1d4',
    secondaryResourceName: null,
    secondaryResourceMax: null,
    weaponCompetencies: ['Medium Melee', 'Heavy Melee'],
    armorCompetencies: ['Light', 'Heavy', 'Shield'],
    classPerks: [
      {
        id: 'sentinel-perk-1',
        name: 'Bastion',
        description: 'Gain +1 DR permanently.',
      },
      {
        id: 'sentinel-perk-2',
        name: 'Vigilance',
        description: 'Cannot be surprised; gain Benefit on all initiative checks.',
      },
    ],
    startingArtifactCapacity: 1,
  },
]

export const CLASS_MAP = Object.fromEntries(CLASSES.map((c) => [c.name, c])) as Record<
  string,
  ClassDefinition
>
